name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [17, 21, 24-ea]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          cache: maven

      - name: JDK Tests ${{ matrix.jdk }}
        run: ./mvnw -B clean install artifact:compare -Dmaven.test.failure.ignore=true -Dansi.strip=true

      - name: Test Logs
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: ${{ matrix.jdk }}-test-results
          path: "**/target/*-reports*/**/TEST-*.xml"
