name: 'Test Report'
on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [17, 21, 24-ea]
    steps:
      - name: Download Surefire Report Artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: ${{ matrix.jdk }}-test-results
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          path: ${{ matrix.jdk }}

      - uses: rigazilla/action-surefire-report@summary
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Test Report Result ${{ matrix.jdk }}
          commit: ${{ github.event.workflow_run.head_sha }}
          ignore_flaky_tests: true
          summary: "Result from workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"
          report_paths: |
            ${{ matrix.jdk }}/**/*-reports*/**/TEST-*.xml
